spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 5
      schema: samaia
    data-username:
  application:
    name: person-service

server:
  servlet:
    context-path: /api
  port: 8081

eureka:
  client:
    service-url:
      defaul-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
